export const ADD_SYMBOLS = 'ADD_SYMBOLS';
export const ADD_SYMBOL = 'ADD_SYMBOL';
export const SYMBOLS_FAILED = 'SYMBOLS_FAILED';
export const SYMBOL_LOADING = 'SYMBOL_LOADING';
export const SYMBOL_DELETE = 'SYMBOL_DELETE';

export const ADD_CRYPTOS = 'ADD_CRYPTOS';
export const ADD_CRYPTO = 'ADD_CRYPTO';
export const CRYPTOS_FAILED = 'CRYPTOS_FAILED';
export const CRYPTO_LOADING = 'CRYPTO_LOADING';
export const CRYPTO_DELETE = 'CRYPTO_DELETE';